### ISSUE TITLE
Mod stops clients from joining server with the error Internal Exception: io.netty.handler.codec.EncoderException: com.google.gson.JsonParseException: Fluid Tag in output ingredient

### ISSUE THREAD

**Issue by secretmeister** [EnderiumSmith/CharcoalPit3#2]

**Comment by secretmeister** [comment]
[Create Delight's-1.2.zip](https://github.com/EnderiumSmith/CharcoalPit3/files/9333977/Create.Delight.s-1.2.zip)
this is the instance I was using

**Comment by EnderiumSmith** [comment]
1.18.2 changed how tags work. should be fixed now
